# Generated by Django 4.0.5 on 2022-06-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_area', '0002_alter_event_timestamp_alter_eventmedia_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
