# Generated by Django 4.0.5 on 2022-06-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_area', '0004_event_type_of_situation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, null=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
