# Generated by Django 4.0.5 on 2022-06-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_area', '0005_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('text', models.TextField(null=True)),
            ],
        ),
    ]
