# Generated by Django 4.0.5 on 2022-06-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_area', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(),
        ),
    ]
