# Generated by Django 4.0.5 on 2022-06-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_area', '0007_alter_feedback_email_alter_feedback_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
